# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &6집 | &r'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'

  # 집을 추가하였을 때 출력되는 메시지
  addHome: '집 ''{homeName}''이(가) 추가되었습니다.'

  # 집을 제거 하였을 때 출력되는 메시지
  # {homeName} : 제거한 집 이름
  removeHome: '{homeName}의 집을 제거하였습니다.'

  # 플레이어의 한도를 설정하였을 때 출력되는 메시지
  # {targetPlayer} : 설정한 플레이어 닉네임
  # {limit} : 설정한 한도
  setHomeLimit: '{targetPlayer}의 집 설정 한도를 {limit}로 설정했습니다.'

  # 집으로 이동하였을 때 출력되는 메시지
  # {homeName} : 이동한 집 이름
  teleportHome: '{homeName}(으)로 이동하였습니다.'

errorMessages:
  # 집을 추가할 수 있는 한도가 초과되었을 때 출력되는 메시지
  limitHomeAmount: '&c집 추가 한도를 초과했습니다.'

  # 중복된 집 이름일 때 출력되는 메시지
  # {homeName} : 집 이름
  alreadyHomeName: '&c집 ''{homeName}''이(가) 이미 존재합니다.'

  # 집 이름을 입력하지 않았을 때 출력되는 메시지
  noHomeName: '&c집 이름을 입력해주세요.'

  # 플레이어 닉네임을 입력하지 않았을 때 출력되는 메시지
  noPlayerName: '&c플레이어 닉네임을 입력해주세요.'

  # 한도를 입력하지 않았을 때 출력되는 메시지
  noLimitAmount: '&c설정할 한도를 입력해주세요.'

  # 유효한 한도 값을 입력하지 않았을 때 출력되는 메시지
  noVaildLimitAmount: '&c유효한 한도 값을 입력해주세요.'

  # 권한이 없을 때 출력되는 메시지
  noPermission: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'

  # 콘솔에서 사용할 수 없는 명령어를 사용하였을 때 출력되는 메시지
  noConsoleCommand: '&c해당 명령어는 플레이어만 사용할 수 있습니다.'

  # 존재하지 않는 명령어일 때 출력되는 메시지
  notExistCommand: '&c존재하지 않는 명령어입니다.'

  # 집이 존재하지 않았을 때 출력되는 메시지
  noHomeExists: '&c존재하지 않는 집입니다.'